### ISSUE TITLE
'rm' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by ittechsathish** [onixjs/starter#1]
When i use this module in windows, npm is throwing error like 'rm' is not recognized as an internal or external command, After changeing rm to 'del', another error " '.' is not recognized as an internal or external command, "

**Comment by jonathan-casarrubias** [comment]
Hey @ittechsathish thanks for reporting,

So, I think in order to fix this we would need to remove the clean from the build and create a new script

```json
{
  "scripts": {
    "build": "npm run lint:fix && node_modules/.bin/tsc",
    "start": "npm run build && node dist/index.js",
    "clean:unix": "rm -rf dist dist6",
    "clean:windows": "del dist dist6",
    "lint": "npm run prettier:check",
    "lint:fix": "npm run prettier:fix",
    "prettier:cli": "prettier \"**/*.ts\" \"**/*.js\"",
    "prettier:check": "npm run prettier:cli -- -l",
    "prettier:fix": "npm run prettier:cli -- --write"
  }
}
```


So you would be required to use the clean commands at other moment rather than building, we might add something more complex to identify the OS and use the right script, for now I think that removing the clean from the build should work.

Please let me know if that works so I can publish a new version, also I removed the './' from the typescript compiler path, so that might be creating the other issue.

I will be looking forward to see if helps so I can push a new version.

Cheers
Jon

**Comment by ittechsathish** [comment]
removing './' is not working ...
